name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: output-docker-tag
        shell: bash
        id: docker-tag
        run: |    
          echo $GITHUB_REF  | cut -d '/' -f3 -
          BRANCH_NAME=`echo $GITHUB_REF | cut -d '/' -f3 -`
          unset IMG_TAGS ; if [[ $BRANCH_NAME == "master" ]]; then IMG_TAGS='latest' ; else IMG_TAGS="$BRANCH_NAME"; fi
          SHA_TAG=`echo $GITHUB_SHA | head -c 6`
          echo $SHA_TAG
          IMG_TAGS="$IMG_TAGS,$SHA_TAG"
          echo $IMG_TAGS
          echo ::set-output name=DOCKER_TAGS::${IMG_TAGS}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: false
          tags: fengkx/node_rssbot:${{steps.docker-tag.outputs.DOCKER_TAGS}}
